// ============================================================
// 40 色色卡 —— 从你提供的两张色卡图片中提取
// 颜色为屏幕提取近似值；如需调整色号或名称，直接改这里即可。
// ============================================================
const PALETTE = [
  { code: '01', name: '黑色',     hex: '#222222' },
  { code: '02', name: '中灰',     hex: '#B4B4B4' },
  { code: '03', name: '米白',     hex: '#EAE7DF' },
  { code: '04', name: '白色',     hex: '#FFFFFF' },
  { code: '05', name: '大红',     hex: '#D32F36' },
  { code: '06', name: '深红',     hex: '#9C0A00' },
  { code: '07', name: '玫红',     hex: '#D60C4A' },
  { code: '08', name: '浅肉粉',   hex: '#E6968D' },
  { code: '09', name: '橙色',     hex: '#FE9875' },
  { code: '10', name: '蜜桃',     hex: '#F7D0C0' },
  { code: '11', name: '奶油粉',   hex: '#FCEFEA' },
  { code: '12', name: '象牙白',   hex: '#FBF6E8' },
  { code: '13', name: '浅驼',     hex: '#DCD2C8' },
  { code: '14', name: '浅卡其',   hex: '#E2CEAB' },
  { code: '15', name: '棕橙',     hex: '#D56322' },
  { code: '16', name: '金棕',     hex: '#D48C42' },
  { code: '17', name: '金黄',     hex: '#F29900' },
  { code: '18', name: '明黄',     hex: '#F9C933' },
  { code: '19', name: '浅黄',     hex: '#FCE499' },
  { code: '20', name: '橄榄灰',   hex: '#B3B47A' },
  { code: '21', name: '黄绿',     hex: '#C2DA72' },
  { code: '22', name: '深橄榄',   hex: '#6C6E00' },
  { code: '23', name: '卡其棕',   hex: '#B19155' },
  { code: '24', name: '摩卡',     hex: '#A98F74' },

  { code: '25', name: '橄榄金',   hex: '#AA9228' },
  { code: '26', name: '深咖啡',   hex: '#3F2B12' },
  { code: '27', name: '红棕',     hex: '#74491F' },
  { code: '28', name: '深紫灰',   hex: '#534658' },
  { code: '29', name: '深靛蓝',   hex: '#2A2446' },
  { code: '30', name: '宝蓝',     hex: '#394599' },
  { code: '31', name: '蓝紫',     hex: '#5A459D' },
  { code: '32', name: '浅紫',     hex: '#BAA3D7' },
  { code: '33', name: '浅蓝',     hex: '#B6BCDF' },
  { code: '34', name: '灰蓝',     hex: '#A9ACBE' },
  { code: '35', name: '青蓝',     hex: '#63ABB9' },
  { code: '36', name: '浅青',     hex: '#B4CFD3' },
  { code: '37', name: '浅天蓝',   hex: '#91D8E6' },
  { code: '38', name: '青绿',     hex: '#47AEA0' },
  { code: '39', name: '薄荷绿',   hex: '#B6D3C8' },
  { code: '40', name: '藏青',     hex: '#273864' },
];
